services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-nest
    ports:
      - 5434:5432
    networks:
      - auth-nest
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-nest
    ports:
      - 5435:5432
    networks:
      - auth-nest
networks:
  auth-nest: